export const GET_MENU_AND_CATEGORY_LOAD = "GET_MENU_AND_CATEGORY_LOAD";
export const GET_MENU_AND_CATEGORY_SUCCESS = "GET_MENU_AND_CATEGORY_SUCCESS";
export const GET_MENU_AND_CATEGORY_FAILED = "GET_MENU_AND_CATEGORY_FAILED";

export const GET_CATEGORY_AND_MENU_LOAD = "GET_CATEGORY_AND_MENU_LOAD";
export const GET_CATEGORY_AND_MENU_SUCCESS = "GET_CATEGORY_AND_MENU_SUCCESS";
export const GET_CATEGORY_AND_MENU_FAILED = "GET_MENU_AND_CATEGORY_FAILED";

export const GET_MENU_BYID_LOAD = "GET_MENU_BYID_LOAD";
export const GET_MENU_BYID_SUCCESS = "GET_MENU_BYID_SUCCESS";
export const GET_MENU_BYID_FAILED = "GET_MENU_BYID_FAILED";

export const CREATE_ORDER_LOAD = "CREATE_ORDER_LOAD";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAILED = "CREATE_ORDER_FAILED";

export const ADD_MENU_TROLLY = "ADD_MENU_TROLLY";
export const EDIT_MENU_TROLLY = "EDIT_MENU_TROLLY";
export const REMOVE_MENU_TROLLY = "REMOVE_MENU_TROLLY";

