import menuimage1 from "../assets/menuimage1.png";
import menuimage2 from "../assets/menuimage2.png";
import menuimage3 from "../assets/menuimage3.png";
import menuimage4 from "../assets/menuimage4.png";

export default [
  {
    title: "Rice chicken and spicies",
    sub_title: "spicy chicken red BBQ",
    colories: "105 calories",
    category: "makanan",
    price: "#14,000",
    image_path: menuimage1,
  },
  {
    title: "Amala with gbegiri",
    sub_title: "amala and ewedu",
    colories: "109 calories",
    category: "minuman",
    price: "#20,000",
    image_path: menuimage2,
  },
  {
    title: "Fufu and tuwo salad",
    sub_title: "spicy chicken red BBQ",
    colories: "116 calories",
    category: "makanan",
    price: "#12,000",
    image_path: menuimage3,
  },
  {
    title: "Ofansala ukwobi",
    sub_title: "ukwobi prepared",
    colories: "98 calories",
    category: "minuman",
    price: "#7,000",
    image_path: menuimage4,
  },
  {
    title: "Rice chicken and spicies",
    sub_title: "spicy chicken red BBQ",
    colories: "105 calories",
    category: "makanan",
    price: "#14,000",
    image_path: menuimage1,
  },
  {
    title: "Amala with gbegiri",
    sub_title: "amala and ewedu",
    colories: "109 calories",
    category: "minuman",
    price: "#20,000",
    image_path: menuimage2,
  },
  {
    title: "Fufu and tuwo salad",
    sub_title: "spicy chicken red BBQ",
    colories: "116 calories",
    category: "makanan",
    price: "#12,000",
    image_path: menuimage3,
  },
  {
    title: "Ofansala ukwobi",
    sub_title: "ukwobi prepared",
    colories: "98 calories",
    category: "minuman",
    price: "#7,000",
    image_path: menuimage4,
  },
  {
    title: "Rice chicken and spicies",
    sub_title: "spicy chicken red BBQ",
    colories: "105 calories",
    category: "makanan",
    price: "#14,000",
    image_path: menuimage1,
  },
  {
    title: "Amala with gbegiri",
    sub_title: "amala and ewedu",
    colories: "109 calories",
    category: "minuman",
    price: "#20,000",
    image_path: menuimage2,
  },
  {
    title: "Fufu and tuwo salad",
    sub_title: "spicy chicken red BBQ",
    colories: "116 calories",
    category: "makanan",
    price: "#12,000",
    image_path: menuimage3,
  },
  {
    title: "Ofansala ukwobi",
    sub_title: "ukwobi prepared",
    colories: "98 calories",
    category: "minuman",
    price: "#7,000",
    image_path: menuimage4,
  },
  {
    title: "Rice chicken and spicies",
    sub_title: "spicy chicken red BBQ",
    colories: "105 calories",
    category: "makanan",
    price: "#14,000",
    image_path: menuimage1,
  },
  {
    title: "Amala with gbegiri",
    sub_title: "amala and ewedu",
    colories: "109 calories",
    category: "minuman",
    price: "#20,000",
    image_path: menuimage2,
  },
  {
    title: "Fufu and tuwo salad",
    sub_title: "spicy chicken red BBQ",
    colories: "116 calories",
    category: "makanan",
    price: "#12,000",
    image_path: menuimage3,
  },
  {
    title: "Ofansala ukwobi",
    sub_title: "ukwobi prepared",
    colories: "98 calories",
    category: "minuman",
    price: "#7,000",
    image_path: menuimage4,
  },
  {
    title: "Rice chicken and spicies",
    sub_title: "spicy chicken red BBQ",
    colories: "105 calories",
    category: "makanan",
    price: "#14,000",
    image_path: menuimage1,
  },
  {
    title: "Amala with gbegiri",
    sub_title: "amala and ewedu",
    colories: "109 calories",
    category: "minuman",
    price: "#20,000",
    image_path: menuimage2,
  },
  {
    title: "Fufu and tuwo salad",
    sub_title: "spicy chicken red BBQ",
    colories: "116 calories",
    category: "makanan",
    price: "#12,000",
    image_path: menuimage3,
  },
  {
    title: "Ofansala ukwobi",
    sub_title: "ukwobi prepared",
    colories: "98 calories",
    category: "minuman",
    price: "#7,000",
    image_path: menuimage4,
  },
];
